title: Mich Lin
logo: /assets/images/headshot_pp.JPG
description: Aerospace Engineer, Activist, Adventurer
email: shuyulin [at] mit [dot] edu
blank_title: true
show_downloads: false


theme: jekyll-theme-minimal
